---
apiVersion: v1
kind: Service
metadata:
  name: applicationname-api
spec:
  selector:
    app: applicationname-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
