---
apiVersion: v1
kind: Service
metadata:
  name: applicationname-database
spec:
  selector:
    app: applicationname-database
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
