---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./../../base
images:
  - name: applicationname-worker
    newName: 192.168.100.2:32000/applicationname-worker
    newTag: latest
