apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationname-api
spec:
  template:
    spec:
      containers:
        - name: applicationname-api
          securityContext:
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 20000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
