---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./../../base
patches:
  - patch: |-
      - op: replace
        path: '/spec/hostname'
        value: 'applicationname.kube.local'
      - op: add
        path: '/spec/cors/origins/-'
        value: 'http://applicationname.kube.local'
      - op: add
        path: '/spec/cors/origins/-'
        value: 'http://localhost:4200'
    target:
      kind: Mapping
      name: applicationname-api
  - patch: |-
      - op: replace
        path: '/spec/hostname'
        value: 'applicationname.kube.local'
      - op: add
        path: '/spec/cors/origins/-'
        value: 'http://applicationname.kube.local'
      - op: add
        path: '/spec/cors/origins/-'
        value: 'http://localhost:4200'
    target:
      kind: Mapping
      name: applicationname-api-hub
images:
  - name: applicationname-api
    newName: '192.168.100.2:32000/applicationname-api'
    newTag: 'latest'
