---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./../../base
images:
  - name: applicationname-worker
    newName: dockerregistry.voortman.net/applicationname-worker
    newTag: '{{IMAGE_TAG}}'
