---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./../../base
patches:
  - patch: |-
      - op: replace
        path: '/spec/hostname'
        value: 'applicationname.{{HOSTNAME}}'
      - op: add
        path: '/spec/cors/origins/-'
        value: 'http://applicationname.{{HOSTNAME}}'
    target:
      kind: Mapping
      name: applicationname-api
  - patch: |-
      - op: replace
        path: '/spec/hostname'
        value: 'applicationname.{{HOSTNAME}}'
      - op: add
        path: '/spec/cors/origins/-'
        value: 'http://applicationname.{{HOSTNAME}}'
    target:
      kind: Mapping
      name: applicationname-api-hub
  - path: './patches/api/patch-security-context.yaml'
images:
  - name: applicationname-api
    newName: '{{REGISTRY}}/applicationname-api'
    newTag: '{{IMAGE_TAG}}'
