---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./../../base
patches:
  - path: './patches/worker/patch-security-context.yaml'
images:
  - name: applicationname-worker
    newName: '{{REGISTRY}}/applicationname-worker'
    newTag: '{{IMAGE_TAG}}'
