apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationname-web
spec:
  template:
    spec:
      containers:
        - name: applicationname-web
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
