---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./../../base
patches:
  - patch: |-
      - op: replace
        path: '/spec/hostname'
        value: 'applicationname.devkube.voortman.net'
      - op: add
        path: '/spec/cors/origins/-'
        value: 'http://applicationname.devkube.voortman.net'
    target:
      kind: Mapping
      name: applicationname-api
  - patch: |-
      - op: replace
        path: '/spec/hostname'
        value: 'applicationname.devkube.voortman.net'
      - op: add
        path: '/spec/cors/origins/-'
        value: 'http://applicationname.devkube.voortman.net'
    target:
      kind: Mapping
      name: applicationname-api-hub
images:
  - name: applicationname-api
    newName: 'dockerregistry.voortman.net/applicationname-api'
    newTag: '{{IMAGE_TAG}}'
