---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./../../base
patches:
  - patch: |-
      - op: replace
        path: '/spec/hostname'
        value: 'applicationname.kube.local'
    target:
      kind: Mapping
      name: applicationname-web
configMapGenerator:
  - name: applicationname-web-config
    literals:
      - 'applicationname-url=http://applicationname.kube.local'
      - 'internationalization-url=http://internationalization.kube.local'
images:
  - name: applicationname-web
    newName: 192.168.100.2:32000/applicationname-web
    newTag: 'latest'
