---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./../../base
patches:
  - patch: |-
      - op: replace
        path: '/spec/hostname'
        value: 'applicationname.{{DEV_HOSTNAME}}'
    target:
      kind: Mapping
      name: applicationname-web
configMapGenerator:
  - name: applicationname-web-config
    literals:
      - 'applicationname-url=http://applicationname.{{DEV_HOSTNAME}}'
      - 'internationalization-url=http://internationalization.{{DEV_HOSTNAME}}'
images:
  - name: applicationname-web
    newName: '{{DEV_REGISTRY}}/applicationname-web'
    newTag: '{{IMAGE_TAG}}'
