---
apiVersion: k8s.ftechmax.net/v1alpha1
kind: FerretDbUser
metadata:
  name: applicationname-database
spec:
  database: applicationname_snake
  secret: applicationname-database
  roles:
    - readWrite
    - dbAdmin
