---
apiVersion: v1
kind: Service
metadata:
  name: applicationname-web
spec:
  selector:
    app: applicationname-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
