name: Pull request build

on:
  merge_group:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build merge result
    runs-on: [ubuntu-latest]
    container: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test api
        run: dotnet test ./src/templates/msa-api/ApplicationName.Api.sln

      - name: Test worker
        run: dotnet test ./src/templates/msa-worker/ApplicationName.Worker.sln

      - name: Build package
        run: dotnet pack ./src/MSA.Templates.sln -c Release
