name: Pull request

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Build and test api / worker
    runs-on: [ubuntu-latest]
    container: 
      image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test api
        run: dotnet test ./src/templates/api/ApplicationName.Api.sln

      - name: Test worker
        run: dotnet test ./src/templates/worker/ApplicationName.Worker.sln

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
          preferLatestVersion: true

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true

      - name: Build package
        run: dotnet pack ./src/MSA.Templates.sln -p:PackageVersion=${{ steps.gitversion.outputs.semVer }} -c Release

  test-web:
    name: Build and test web
    runs-on: ubuntu-latest
    container: 
      image: node:lts-alpine
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
          
      # - name: Run Unit Tests
      #   run: npm run test
        
      - name: Build Application
        run: npm run build