name: Pull request build

on:
  merge_group:
  pull_request:
     types: [opened, synchronize]

jobs:
  build:
    name: Build merge result
    runs-on: [self-hosted, linux]
    container: mcr.microsoft.com/dotnet/sdk:7.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: dotnet build

