name: Pull request

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Tests
    runs-on: [ubuntu-latest]
    container: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test api
        run: dotnet test ./src/templates/api/ApplicationName.Api.sln

      - name: Test worker
        run: dotnet test ./src/templates/worker/ApplicationName.Worker.sln

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          preferLatestVersion: true

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Build package
        run: dotnet pack ./src/MSA.Templates.sln -p:PackageVersion=${{ steps.gitversion.outputs.semVer }} -c Release
