name: Release package

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release package
    runs-on: [ubuntu-latest]
    container: mcr.microsoft.com/dotnet/sdk:7.0-alpine
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '6.x'
          preferLatestVersion: true

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Pack code to package
        run: dotnet pack MSA.Templates.csproj -c Release --include-symbols

      - name: Ship package
        run: dotnet nuget push $GITHUB_WORKSPACE/**/*.symbols.nupkg -k ${{ secrets.CI_NUGET_TOKEN }} -s ${{ secrets.CI_NUGET_RELEASE_REPO }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gitversion.outputs.semVer }}
          commit: 'main'
          name: Release ${{ steps.gitversion.outputs.semVer }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
